
name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js '18.13'
        uses: actions/setup-node@v3
        with:
          node-version: '18.13'
          cache: 'pnpm'
      - run: |
          pnpm install
          pnpm build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: dist/

