name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: build front and back
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          tar -zcvf static.tar.gz ./static/
          zip -r static.zip ./static/
          ls

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            static.tar.gz
            static.zip
          token: ${{ secrets.TOKEN }}
          generate_release_notes: true

